"""article

Revision ID: 1647397b4156
Revises: 569986eefcce
Create Date: 2026-01-17 19:17:24.739931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1647397b4156'
down_revision: Union[str, Sequence[str], None] = '569986eefcce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bookmarks', ['user_id', 'article_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookmarks', type_='unique')
    # ### end Alembic commands ###
