"""article

Revision ID: 514fbef3f3ca
Revises: bf247f73d303
Create Date: 2026-01-14 20:39:00.529187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '514fbef3f3ca'
down_revision: Union[str, Sequence[str], None] = 'bf247f73d303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('articles', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('articles', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('articles', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('articles', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
