"""hello

Revision ID: 5d594fa30a29
Revises: 78ecac790aea
Create Date: 2026-01-10 19:30:17.737965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d594fa30a29'
down_revision: Union[str, Sequence[str], None] = '78ecac790aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('categories_slug_key'), 'categories', type_='unique')
    op.drop_column('categories', 'slug')
    op.drop_column('categories', 'seo_description')
    op.drop_column('categories', 'seo_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('seo_title', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('seo_description', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('slug', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('categories_slug_key'), 'categories', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_column('categories', 'updated_at')
    # ### end Alembic commands ###
