"""hello

Revision ID: a45e453eb5d6
Revises: 7a7dd2ec7c8f
Create Date: 2026-01-13 21:16:12.095736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a45e453eb5d6'
down_revision: Union[str, Sequence[str], None] = '7a7dd2ec7c8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('articles', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('articles', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('articles', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('articles', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
